// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import "github.com/mndon/gf-extensions/delayqueuex/internal/dao/internal"

// internalDelayQueueDao is internal type for wrapping internal DAO implements.
type internalDelayQueueDao = *internal.DelayQueueDao

// delayQueueDao is the data access object for table delay_queue.
// You can define custom methods on it to extend its functionality as you wish.
type delayQueueDao struct {
	internalDelayQueueDao
}

var (
	// DelayQueue is globally public accessible object for table delay_queue operations.
	DelayQueue = delayQueueDao{
		internal.NewDelayQueueDao(),
	}
)

// Fill with you ideas below.
