// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mndon/gf-extensions/adminx/internal/dao/internal"
)

// internalAdminConfigDao is internal type for wrapping internal DAO implements.
type internalAdminConfigDao = *internal.AdminConfigDao

// adminConfigDao is the data access object for table admin_config.
// You can define custom methods on it to extend its functionality as you wish.
type adminConfigDao struct {
	internalAdminConfigDao
}

var (
	// AdminConfig is globally public accessible object for table admin_config operations.
	AdminConfig = adminConfigDao{
		internal.NewAdminConfigDao(),
	}
)

// Fill with you ideas below.
