// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mndon/gf-extensions/adminx/internal/dao/internal"
)

// internalAdminAuthRuleDao is internal type for wrapping internal DAO implements.
type internalAdminAuthRuleDao = *internal.AdminAuthRuleDao

// adminAuthRuleDao is the data access object for table admin_auth_rule.
// You can define custom methods on it to extend its functionality as you wish.
type adminAuthRuleDao struct {
	internalAdminAuthRuleDao
}

var (
	// AdminAuthRule is globally public accessible object for table admin_auth_rule operations.
	AdminAuthRule = adminAuthRuleDao{
		internal.NewAdminAuthRuleDao(),
	}
)

// Fill with you ideas below.
