// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mndon/gf-extensions/adminx/internal/dao/internal"
)

// internalAdminOperLogDao is internal type for wrapping internal DAO implements.
type internalAdminOperLogDao = *internal.AdminOperLogDao

// adminOperLogDao is the data access object for table admin_oper_log.
// You can define custom methods on it to extend its functionality as you wish.
type adminOperLogDao struct {
	internalAdminOperLogDao
}

var (
	// AdminOperLog is globally public accessible object for table admin_oper_log operations.
	AdminOperLog = adminOperLogDao{
		internal.NewAdminOperLogDao(),
	}
)

// Fill with you ideas below.
