// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mndon/gf-extensions/adminx/internal/dao/internal"
)

// internalAdminCasbinRuleDao is internal type for wrapping internal DAO implements.
type internalAdminCasbinRuleDao = *internal.AdminCasbinRuleDao

// adminCasbinRuleDao is the data access object for table admin_casbin_rule.
// You can define custom methods on it to extend its functionality as you wish.
type adminCasbinRuleDao struct {
	internalAdminCasbinRuleDao
}

var (
	// AdminCasbinRule is globally public accessible object for table admin_casbin_rule operations.
	AdminCasbinRule = adminCasbinRuleDao{
		internal.NewAdminCasbinRuleDao(),
	}
)

// Fill with you ideas below.
