// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/mndon/gf-extensions/adminx/internal/dao/internal"
)

// internalAdminDictDataDao is internal type for wrapping internal DAO implements.
type internalAdminDictDataDao = *internal.AdminDictDataDao

// adminDictDataDao is the data access object for table admin_dict_data.
// You can define custom methods on it to extend its functionality as you wish.
type adminDictDataDao struct {
	internalAdminDictDataDao
}

var (
	// AdminDictData is globally public accessible object for table admin_dict_data operations.
	AdminDictData = adminDictDataDao{
		internal.NewAdminDictDataDao(),
	}
)

// Fill with you ideas below.
