// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/mndon/gf-extensions/adminx/internal/api"
)

type IAdminDictData interface {
	GetDictWithDataByType(ctx context.Context, dictType, defaultValue string) (dict *api.GetDictRes, err error)
	List(ctx context.Context, req *api.DictDataSearchReq) (res *api.DictDataSearchRes, err error)
	Add(ctx context.Context, req *api.DictDataAddReq, userId uint64) (err error)
	Get(ctx context.Context, dictCode uint) (res *api.DictDataGetRes, err error)
	Edit(ctx context.Context, req *api.DictDataEditReq, userId uint64) (err error)
	Delete(ctx context.Context, ids []int) (err error)
}

var localAdminDictData IAdminDictData

func AdminDictData() IAdminDictData {
	if localAdminDictData == nil {
		panic("implement not found for interface IAdminDictData, forgot register?")
	}
	return localAdminDictData
}

func RegisterAdminDictData(i IAdminDictData) {
	localAdminDictData = i
}
