// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/mndon/gf-extensions/adminx/internal/api"
	"github.com/mndon/gf-extensions/adminx/internal/model"
	"github.com/mndon/gf-extensions/adminx/internal/model/entity"
)

type (
	IAdminAuthRule interface {
		GetMenuListSearch(ctx context.Context, req *api.RuleSearchReq) (res []*model.AdminAuthRuleInfoRes, err error)
		GetIsMenuList(ctx context.Context) ([]*model.AdminAuthRuleInfoRes, error)
		GetMenuList(ctx context.Context) (list []*model.AdminAuthRuleInfoRes, err error)
		GetIsButtonList(ctx context.Context) ([]*model.AdminAuthRuleInfoRes, error)
		Add(ctx context.Context, req *api.RuleAddReq) (err error)
		BindRoleRule(ctx context.Context, ruleId interface{}, roleIds []uint) (err error)
		Get(ctx context.Context, id uint) (rule *entity.AdminAuthRule, err error)
		GetMenuRoles(ctx context.Context, id uint) (roleIds []uint, err error)
		Update(ctx context.Context, req *api.RuleUpdateReq) (err error)
		UpdateRoleRule(ctx context.Context, ruleId uint, roleIds []uint) (err error)
		GetMenuListTree(pid uint, list []*model.AdminAuthRuleInfoRes) []*model.AdminAuthRuleTreeRes
		DeleteMenuByIds(ctx context.Context, ids []int) (err error)
		FindSonByParentId(list []*model.AdminAuthRuleInfoRes, pid uint) []*model.AdminAuthRuleInfoRes
	}
)

var (
	localAdminAuthRule IAdminAuthRule
)

func AdminAuthRule() IAdminAuthRule {
	if localAdminAuthRule == nil {
		panic("implement not found for interface IAdminAuthRule, forgot register?")
	}
	return localAdminAuthRule
}

func RegisterAdminAuthRule(i IAdminAuthRule) {
	localAdminAuthRule = i
}
