// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/mndon/gf-extensions/adminx/internal/api"
	"github.com/mndon/gf-extensions/adminx/internal/model"

	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IOperateLog interface {
		OperationLog(r *ghttp.Request)
		Invoke(ctx context.Context, data *model.AdminOperLogAdd)
		List(ctx context.Context, req *api.AdminOperLogSearchReq) (listRes *api.AdminOperLogSearchRes, err error)
		GetByOperId(ctx context.Context, operId uint64) (res *model.AdminOperLogInfoRes, err error)
		DeleteByIds(ctx context.Context, ids []uint64) (err error)
		ClearLog(ctx context.Context) (err error)
	}
)

var (
	localOperateLog IOperateLog
)

func OperateLog() IOperateLog {
	if localOperateLog == nil {
		panic("implement not found for interface IOperateLog, forgot register?")
	}
	return localOperateLog
}

func RegisterOperateLog(i IOperateLog) {
	localOperateLog = i
}
