// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/mndon/gf-extensions/adminx/internal/api"
	"github.com/mndon/gf-extensions/adminx/internal/model"
)

type IAdminLoginLog interface {
	Invoke(ctx context.Context, data *model.LoginLogParams)
	List(ctx context.Context, req *api.LoginLogSearchReq) (res *api.LoginLogSearchRes, err error)
	DeleteLoginLogByIds(ctx context.Context, ids []int) (err error)
	ClearLoginLog(ctx context.Context) (err error)
}

var localAdminLoginLog IAdminLoginLog

func AdminLoginLog() IAdminLoginLog {
	if localAdminLoginLog == nil {
		panic("implement not found for interface IAdminLoginLog, forgot register?")
	}
	return localAdminLoginLog
}

func RegisterAdminLoginLog(i IAdminLoginLog) {
	localAdminLoginLog = i
}
