// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/mndon/gf-extensions/adminx/internal/api"
	"github.com/mndon/gf-extensions/adminx/internal/model/entity"
)

type IAdminConfig interface {
	List(ctx context.Context, req *api.ConfigSearchReq) (res *api.ConfigSearchRes, err error)
	Add(ctx context.Context, req *api.ConfigAddReq, userId uint64) (err error)
	CheckConfigKeyUnique(ctx context.Context, configKey string, configId ...int64) (err error)
	Get(ctx context.Context, id int) (res *api.ConfigGetRes, err error)
	Edit(ctx context.Context, req *api.ConfigEditReq, userId uint64) (err error)
	Delete(ctx context.Context, ids []int) (err error)
	GetConfigByKey(ctx context.Context, key string) (config *entity.AdminConfig, err error)
	GetByKey(ctx context.Context, key string) (config *entity.AdminConfig, err error)
}

var localAdminConfig IAdminConfig

func AdminConfig() IAdminConfig {
	if localAdminConfig == nil {
		panic("implement not found for interface IAdminConfig, forgot register?")
	}
	return localAdminConfig
}

func RegisterAdminConfig(i IAdminConfig) {
	localAdminConfig = i
}
