// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/mndon/gf-extensions/adminx/internal/api"
	"github.com/mndon/gf-extensions/adminx/internal/model/entity"
)

type (
	IAdminRole interface {
		GetRoleListSearch(ctx context.Context, req *api.RoleListReq) (res *api.RoleListRes, err error)
		GetRoleList(ctx context.Context) (list []*entity.AdminRole, err error)
		AddRoleRule(ctx context.Context, ruleIds []uint, roleId int64) (err error)
		DelRoleRule(ctx context.Context, roleId int64) (err error)
		AddRole(ctx context.Context, req *api.RoleAddReq) (err error)
		Get(ctx context.Context, id uint) (res *entity.AdminRole, err error)
		GetFilteredNamedPolicy(ctx context.Context, id uint) (gpSlice []int, err error)
		EditRole(ctx context.Context, req *api.RoleEditReq) (err error)
		DeleteByIds(ctx context.Context, ids []int64) (err error)
	}
)

var (
	localAdminRole IAdminRole
)

func AdminRole() IAdminRole {
	if localAdminRole == nil {
		panic("implement not found for interface IAdminRole, forgot register?")
	}
	return localAdminRole
}

func RegisterAdminRole(i IAdminRole) {
	localAdminRole = i
}
