// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminAuthRule"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminConfig"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminDictData"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminDictType"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminLoginLog"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminOperLog"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminRole"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminUser"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/adminUserOnline"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/cache"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/context"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/eventBus"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/middleware"
	_ "github.com/mndon/gf-extensions/adminx/internal/logic/token"
)
